# Generated by Django 5.0.7 on 2024-08-02 15:30

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to='productos/'),
        ),
    ]
